// Code generated by MockGen. DO NOT EDIT.
// Source: usecase/usecase.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "github.com/VysMax/organizational-structure/models"
	gomock "github.com/golang/mock/gomock"
)

// MockOrganizationRepository is a mock of OrganizationRepository interface.
type MockOrganizationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOrganizationRepositoryMockRecorder
}

// MockOrganizationRepositoryMockRecorder is the mock recorder for MockOrganizationRepository.
type MockOrganizationRepositoryMockRecorder struct {
	mock *MockOrganizationRepository
}

// NewMockOrganizationRepository creates a new mock instance.
func NewMockOrganizationRepository(ctrl *gomock.Controller) *MockOrganizationRepository {
	mock := &MockOrganizationRepository{ctrl: ctrl}
	mock.recorder = &MockOrganizationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrganizationRepository) EXPECT() *MockOrganizationRepositoryMockRecorder {
	return m.recorder
}

// CheckExistence mocks base method.
func (m *MockOrganizationRepository) CheckExistence(parentID int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckExistence", parentID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckExistence indicates an expected call of CheckExistence.
func (mr *MockOrganizationRepositoryMockRecorder) CheckExistence(parentID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckExistence", reflect.TypeOf((*MockOrganizationRepository)(nil).CheckExistence), parentID)
}

// CreateDepartment mocks base method.
func (m *MockOrganizationRepository) CreateDepartment(department *models.Department) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDepartment", department)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateDepartment indicates an expected call of CreateDepartment.
func (mr *MockOrganizationRepositoryMockRecorder) CreateDepartment(department interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDepartment", reflect.TypeOf((*MockOrganizationRepository)(nil).CreateDepartment), department)
}

// CreateEmployee mocks base method.
func (m *MockOrganizationRepository) CreateEmployee(employee *models.Employee) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEmployee", employee)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateEmployee indicates an expected call of CreateEmployee.
func (mr *MockOrganizationRepositoryMockRecorder) CreateEmployee(employee interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEmployee", reflect.TypeOf((*MockOrganizationRepository)(nil).CreateEmployee), employee)
}

// DeleteDepartment mocks base method.
func (m *MockOrganizationRepository) DeleteDepartment(params *models.RequestDelete) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDepartment", params)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDepartment indicates an expected call of DeleteDepartment.
func (mr *MockOrganizationRepositoryMockRecorder) DeleteDepartment(params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDepartment", reflect.TypeOf((*MockOrganizationRepository)(nil).DeleteDepartment), params)
}

// GetTree mocks base method.
func (m *MockOrganizationRepository) GetTree(params *models.RequestTree) (*models.Department, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTree", params)
	ret0, _ := ret[0].(*models.Department)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTree indicates an expected call of GetTree.
func (mr *MockOrganizationRepositoryMockRecorder) GetTree(params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTree", reflect.TypeOf((*MockOrganizationRepository)(nil).GetTree), params)
}

// UpdateParent mocks base method.
func (m *MockOrganizationRepository) UpdateParent(department *models.Department) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateParent", department)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateParent indicates an expected call of UpdateParent.
func (mr *MockOrganizationRepositoryMockRecorder) UpdateParent(department interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateParent", reflect.TypeOf((*MockOrganizationRepository)(nil).UpdateParent), department)
}
